services:
  supportal_django:
    container_name: supportal_django
    build: .
    restart: unless-stopped
    depends_on:
      - supportal_postgres
    env_file:
      - .env
    networks:
      - supportal_network
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      # - supportal_django_static_volume:/app/staticfiles
      # - supportal_django_media_volume:/app/apps/media
  supportal_postgres:
    image: postgres:17
    container_name: supportal_postgres
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - supportal_postgres_volume:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - supportal_network
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - supportal_network
  redis:
    image: redis:8
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_volume:/data
    ports:
      - "6379:6379"
    command: redis-server --requirepass $REDIS_PASSWORD --appendonly yes
    env_file:
      - .env
    networks:
      - supportal_network
  # other services

  # webserver_nginx:
  #   build:
  #     context: ./nginx
  #   container_name: webserver_nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - users_django
  #     - notifications_django
  #   networks:
  #     - web_network
  #   volumes:
  #     - users_static_volume:/users/static
  #     - users_media_volume:/users/media
  #     - notifications_static_volume:/notifications/static
  #     - notifications_media_volume:/notifications/media
  #     - landing_static_volume:/landing/static
  #     - landing_media_volume:/landing/media
  #     - products_static_volume:/products/static
  #     - products_media_volume:/products/media
networks:
  supportal_network:
    driver: bridge

volumes:
  supportal_postgres_volume:
    name: supportal_postgres_volume
  redis_volume:
    name: redis_volume
  # supportal_django_static_volume:
  #   name: supportal_django_static_volume
  # supportal_django_media_volume:
  #   name: supportal_django_media_volume
