[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
asgiref = "3.8.1"
async-timeout = "4.0.3"
attrs = "24.2.0"
autobahn = "24.4.2"
automat = "24.8.0"
cffi = "1.17.0"
channels = "4.1.0"
channels-redis = "4.2.0"
constantly = "23.10.4"
cryptography = "43.0.0"
daphne = "4.1.2"
django = "5.1"
django-cors-headers = "4.4.0"
django-filter = "24.3"
djangorestframework = "3.15.2"
djangorestframework-simplejwt = "5.3.1"
drf-spectacular = "0.27.2"
gunicorn = "23.0.0"
hyperlink = "21.0.0"
idna = "3.7"
incremental = "24.7.2"
inflection = "0.5.1"
jsonschema = "4.23.0"
jsonschema-specifications = "2023.12.1"
markdown = "3.6"
msgpack = "1.0.8"
packaging = "24.1"
pillow = "10.4.0"
psycopg-binary = "3.2.1"
psycopg2-binary = "2.9.9"
pyasn1 = "0.6.0"
pyasn1-modules = "0.4.0"
pycparser = "2.22"
pyjwt = "2.9.0"
pyopenssl = "24.2.1"
python-dotenv = "1.0.1"
pyyaml = "6.0.2"
redis = "5.0.8"
referencing = "0.35.1"
rpds-py = "0.20.0"
ruff = "0.6.0"
service-identity = "24.1.0"
sqlparse = "0.5.1"
tomli = "2.0.1"
twisted = "24.7.0"
txaio = "23.1.1"
typing-extensions = "4.12.2"
uritemplate = "4.1.1"
zope-interface = "7.0.1"
environ = {extras = ["django"], version = "^1.0"}
django-environ = "^0.12.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88
target-version = "py310"
extend-select = ["I", "C4", "UP", "YTT", "TID", "SIM", "Q", "RUF100", "F"]
fix = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
docstring-code-format = true

[tool.ruff.lint]
select = [
    "F",     # pyflakes
    "E",     # pycodestyle errors
    "W",     # pycodestyle warnings
    "C90",   # mccabe complexity
    "I",     # isort
    "B",     # flake8-bugbear
    "TID",   # flake8-tidy-imports
    "UP",    # pyupgrade
    "Q",     # flake8-quotes
    "RUF",   # Ruff-specific rules
]
ignore = []

[tool.ruff.lint.isort]
force-single-line = false
known-first-party = ["your_package"]
lines-after-imports = 2
combine-as-imports = true