# Generated by Django 5.1 on 2024-08-15 23:47

import chatapp.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, default=chatapp.utils.models.generate_random_number, max_length=4, verbose_name='OTP Code'),
        ),
    ]
