# Generated by Django 5.1 on 2024-08-16 15:25

import chatapp.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='no_avatar.jpg', upload_to=chatapp.utils.models.upload_location),
        ),
    ]
