# Generated by Django 5.1 on 2024-08-22 10:31

import chatapp.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_options_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, default=chatapp.users.models.generate_otp, max_length=5, verbose_name='OTP Code'),
        ),
    ]
